description: SCUT Electrical and Electronics Engineers

navbar:
  displayTitle: true
  displayLogo: true
  logo:
    path: images/logo.svg
    # dark: images/logo-dark.svg
    # width: 40
    # height: 20
    # link: /
  width: wide

page:
  # full (100%), wide (90rem), normal (1280px)
  width: wide

theme:
  # light | dark | system
  default: system
  displayToggle: true

footer:
  enable: true
  displayCopyright: true
  displayPoweredBy: true
  width: normal

displayUpdatedDate: true
dateFormat: "January 2, 2006"

# Search
# flexsearch is enabled by default
search:
  enable: true
  type: flexsearch

  flexsearch:
    # index page by: content | summary | heading | title
    index: content
    # full | forward | reverse | strict
    # https://github.com/nextapps-de/flexsearch/#tokenizer-prefix-search
    tokenize: forward

editURL:
  enable: true
  base: "https://github.com/scuteee/scuteee/edit/main/content"

blog:
  list:
    displayTags: true
    # date | lastmod | publishDate | title | weight
    sortBy: date
    sortOrder: desc # or "asc"

highlight:
  copy:
    enable: true
    # hover | always
    display: hover

comments:
  enable: false
  type: remark

math:
  renderer: mathjax