hugoVersion:
  extended: true
  min: 0.136.0
imports:
- path: github.com/scuteee/computer-network
  mounts:
  - source: .
    target: content/courses/computer-network
- path: github.com/scuteee/probability-and-statistics
  mounts:
  - source: .
    target: content/courses/probability-and-statistics
- path: github.com/scuteee/analog-integrated-circuit
  mounts:
  - source: .
    target: content/courses/analog-integrated-circuit
- path: github.com/scuteee/signal-and-system
  mounts:
  - source: .
    target: content/courses/signal-and-system
- path: github.com/scuteee/digital-signal-process
  mounts:
  - source: .
    target: content/courses/digital-signal-process
- path: github.com/scuteee/semiconductor-device
  mounts:
  - source: .
    target: content/courses/semiconductor-device
